import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=180)),
                ("code", models.CharField(max_length=80)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("country", models.CharField(default="US", max_length=2)),
                ("grid_region", models.CharField(blank=True, max_length=40)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="facilities", to="ingestion.tenant")),
            ],
            options={"ordering": ["name"], "unique_together": {("tenant", "code")}},
        ),
        migrations.CreateModel(
            name="SourceSystem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="source_systems", to="ingestion.tenant")),
            ],
            options={"ordering": ["kind", "name"], "unique_together": {("tenant", "kind", "name")}},
        ),
        migrations.CreateModel(
            name="EmissionFactor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("activity_kind", models.CharField(max_length=30)),
                ("scope", models.CharField(max_length=20)),
                ("label", models.CharField(max_length=220)),
                ("factor_unit", models.CharField(max_length=40)),
                ("kg_co2e_per_unit", models.DecimalField(decimal_places=8, max_digits=18)),
                ("geography", models.CharField(blank=True, max_length=80)),
                ("source", models.CharField(max_length=220)),
                ("source_url", models.URLField(blank=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="emission_factors", to="ingestion.tenant")),
            ],
            options={"ordering": ["activity_kind", "geography", "label"]},
        ),
        migrations.CreateModel(
            name="ReferenceMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mapping_type", models.CharField(max_length=40)),
                ("source_value", models.CharField(max_length=160)),
                ("normalized_code", models.CharField(max_length=160)),
                ("display_name", models.CharField(max_length=220)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("facility", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="ingestion.facility")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reference_mappings", to="ingestion.tenant")),
            ],
            options={"ordering": ["mapping_type", "source_value"], "unique_together": {("tenant", "mapping_type", "source_value")}},
        ),
        migrations.CreateModel(
            name="IngestionBatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_kind", models.CharField(max_length=20)),
                ("file_name", models.CharField(max_length=255)),
                ("parser_version", models.CharField(default="2026-05-v1", max_length=40)),
                ("status", models.CharField(default="RECEIVED", max_length=20)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("imported_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("warning_count", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_batches", to=settings.AUTH_USER_MODEL)),
                ("source_system", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="batches", to="ingestion.sourcesystem")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="batches", to="ingestion.tenant")),
            ],
            options={"ordering": ["-started_at"]},
        ),
        migrations.CreateModel(
            name="RawSourceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("row_number", models.PositiveIntegerField()),
                ("source_external_id", models.CharField(blank=True, max_length=220)),
                ("row_hash", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="raw_records", to="ingestion.ingestionbatch")),
                ("source_system", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="raw_records", to="ingestion.sourcesystem")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="raw_records", to="ingestion.tenant")),
            ],
            options={"ordering": ["batch_id", "row_number"]},
        ),
        migrations.CreateModel(
            name="ActivityRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.CharField(blank=True, max_length=220)),
                ("activity_kind", models.CharField(max_length=30)),
                ("scope", models.CharField(max_length=20)),
                ("activity_date", models.DateField(blank=True, null=True)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("supplier", models.CharField(blank=True, max_length=220)),
                ("category", models.CharField(blank=True, max_length=180)),
                ("description", models.TextField(blank=True)),
                ("original_quantity", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ("original_unit", models.CharField(blank=True, max_length=40)),
                ("normalized_quantity", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ("normalized_unit", models.CharField(blank=True, max_length=40)),
                ("amount", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("origin", models.CharField(blank=True, max_length=20)),
                ("destination", models.CharField(blank=True, max_length=20)),
                ("review_status", models.CharField(default="NEEDS_REVIEW", max_length=20)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("edited_from_raw", models.BooleanField(default=False)),
                ("source_hash", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_activities", to=settings.AUTH_USER_MODEL)),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="ingestion.ingestionbatch")),
                ("facility", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="ingestion.facility")),
                ("raw_record", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="activity", to="ingestion.rawsourcerecord")),
                ("source_system", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="activities", to="ingestion.sourcesystem")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="ingestion.tenant")),
            ],
            options={"ordering": ["-activity_date", "-id"]},
        ),
        migrations.CreateModel(
            name="ValidationIssue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("severity", models.CharField(max_length=20)),
                ("code", models.CharField(max_length=80)),
                ("field", models.CharField(blank=True, max_length=120)),
                ("message", models.TextField()),
                ("status", models.CharField(default="OPEN", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("activity", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="validation_issues", to="ingestion.activityrecord")),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="validation_issues", to="ingestion.ingestionbatch")),
                ("raw_record", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="validation_issues", to="ingestion.rawsourcerecord")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="validation_issues", to="ingestion.tenant")),
            ],
            options={"ordering": ["severity", "code", "id"]},
        ),
        migrations.CreateModel(
            name="EmissionEstimate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("co2e_kg", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ("calculation_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activity", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="emission_estimate", to="ingestion.activityrecord")),
                ("factor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="ingestion.emissionfactor")),
            ],
        ),
        migrations.CreateModel(
            name="ReviewDecision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("decision", models.CharField(max_length=20)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("activity", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="review_decisions", to="ingestion.activityrecord")),
                ("decided_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="review_decisions", to="ingestion.tenant")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(max_length=80)),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("activity", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="audit_events", to="ingestion.activityrecord")),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("batch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="audit_events", to="ingestion.ingestionbatch")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="audit_events", to="ingestion.tenant")),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="UserMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(max_length=20)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="ingestion.tenant")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"unique_together": {("user", "tenant")}},
        ),
        migrations.AddIndex(
            model_name="referencemapping",
            index=models.Index(fields=["tenant", "mapping_type", "source_value"], name="refmap_tenant_type_value_idx"),
        ),
        migrations.AddIndex(
            model_name="rawsourcerecord",
            index=models.Index(fields=["tenant", "source_system", "row_hash"], name="raw_tenant_source_hash_idx"),
        ),
        migrations.AddIndex(
            model_name="rawsourcerecord",
            index=models.Index(fields=["batch", "row_number"], name="raw_batch_row_idx"),
        ),
        migrations.AddIndex(
            model_name="activityrecord",
            index=models.Index(fields=["tenant", "review_status"], name="activity_tenant_review_idx"),
        ),
        migrations.AddIndex(
            model_name="activityrecord",
            index=models.Index(fields=["tenant", "scope"], name="activity_tenant_scope_idx"),
        ),
        migrations.AddIndex(
            model_name="activityrecord",
            index=models.Index(fields=["tenant", "activity_kind"], name="activity_tenant_kind_idx"),
        ),
        migrations.AddIndex(
            model_name="activityrecord",
            index=models.Index(fields=["tenant", "activity_date"], name="activity_tenant_date_idx"),
        ),
        migrations.AddIndex(
            model_name="validationissue",
            index=models.Index(fields=["tenant", "severity", "status"], name="issue_tenant_sev_status_idx"),
        ),
        migrations.AddIndex(
            model_name="validationissue",
            index=models.Index(fields=["batch", "severity"], name="issue_batch_severity_idx"),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["tenant", "event_type"], name="audit_tenant_event_idx"),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["activity", "created_at"], name="audit_activity_created_idx"),
        ),
    ]

