# Generated by Django 5.0.7 on 2026-05-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activityrecord',
            new_name='ingestion_a_tenant__613d8e_idx',
            old_name='activity_tenant_review_idx',
        ),
        migrations.RenameIndex(
            model_name='activityrecord',
            new_name='ingestion_a_tenant__bea35a_idx',
            old_name='activity_tenant_scope_idx',
        ),
        migrations.RenameIndex(
            model_name='activityrecord',
            new_name='ingestion_a_tenant__b75d75_idx',
            old_name='activity_tenant_kind_idx',
        ),
        migrations.RenameIndex(
            model_name='activityrecord',
            new_name='ingestion_a_tenant__91d654_idx',
            old_name='activity_tenant_date_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='ingestion_a_tenant__5d52db_idx',
            old_name='audit_tenant_event_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='ingestion_a_activit_6a8ac5_idx',
            old_name='audit_activity_created_idx',
        ),
        migrations.RenameIndex(
            model_name='rawsourcerecord',
            new_name='ingestion_r_tenant__f94103_idx',
            old_name='raw_tenant_source_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='rawsourcerecord',
            new_name='ingestion_r_batch_i_46dfe2_idx',
            old_name='raw_batch_row_idx',
        ),
        migrations.RenameIndex(
            model_name='referencemapping',
            new_name='ingestion_r_tenant__1786c5_idx',
            old_name='refmap_tenant_type_value_idx',
        ),
        migrations.RenameIndex(
            model_name='validationissue',
            new_name='ingestion_v_tenant__48e0b8_idx',
            old_name='issue_tenant_sev_status_idx',
        ),
        migrations.RenameIndex(
            model_name='validationissue',
            new_name='ingestion_v_batch_i_2e3819_idx',
            old_name='issue_batch_severity_idx',
        ),
        migrations.AlterField(
            model_name='activityrecord',
            name='activity_kind',
            field=models.CharField(choices=[('FUEL', 'Fuel'), ('PROCUREMENT', 'Procurement'), ('ELECTRICITY', 'Electricity'), ('FLIGHT', 'Flight'), ('HOTEL', 'Hotel'), ('GROUND', 'Ground transport')], max_length=30),
        ),
        migrations.AlterField(
            model_name='activityrecord',
            name='review_status',
            field=models.CharField(choices=[('NEEDS_REVIEW', 'Needs review'), ('BLOCKED', 'Blocked'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked')], default='NEEDS_REVIEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='activityrecord',
            name='scope',
            field=models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=20),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='activity_kind',
            field=models.CharField(choices=[('FUEL', 'Fuel'), ('PROCUREMENT', 'Procurement'), ('ELECTRICITY', 'Electricity'), ('FLIGHT', 'Flight'), ('HOTEL', 'Hotel'), ('GROUND', 'Ground transport')], max_length=30),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='scope',
            field=models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ingestionbatch',
            name='source_kind',
            field=models.CharField(choices=[('SAP', 'SAP fuel/procurement'), ('UTILITY', 'Utility electricity'), ('TRAVEL', 'Corporate travel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ingestionbatch',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='RECEIVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='referencemapping',
            name='mapping_type',
            field=models.CharField(choices=[('PLANT_CODE', 'SAP plant code'), ('MATERIAL_CODE', 'SAP material code'), ('METER_ID', 'Utility meter id'), ('EXPENSE_TYPE', 'Travel expense type'), ('AIRPORT_CODE', 'Airport code')], max_length=40),
        ),
        migrations.AlterField(
            model_name='reviewdecision',
            name='decision',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_INFO', 'Needs info')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sourcesystem',
            name='kind',
            field=models.CharField(choices=[('SAP', 'SAP fuel/procurement'), ('UTILITY', 'Utility electricity'), ('TRAVEL', 'Corporate travel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ANALYST', 'Analyst'), ('AUDITOR', 'Auditor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='validationissue',
            name='severity',
            field=models.CharField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning'), ('INFO', 'Info')], max_length=20),
        ),
        migrations.AlterField(
            model_name='validationissue',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20),
        ),
    ]
